name: Scheduled Plugin Download

on:
  schedule:
    - cron: '0 19 * * *'  # 每天19:00 UTC（北京时间 03:00）
    - cron: '0 8 * * *'    # 每天08:00 UTC（北京时间 16:00）
  push:
    paths:
      - '.github/workflows/**'
      - '*.py'

permissions:
  contents: write

jobs:
  download-plugins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 使用 Python 版本 3.x

    - name: Install dependencies
      run: |
        pip install requests  # 如果有其他依赖，添加到这里

    - name: Run the plugin download script
      run: |
        python script.py  # 将 your_script.py 替换为你的脚本文件名

    - name: Commit and push downloaded plugins
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Loon/*.plugin  # 添加 Loon 文件夹中的所有下载的插件文件
        git commit -m "Add downloaded plugins" || echo "No changes to commit"
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/sooyaaabo/nsloon.git
